# Site settings
title: "Cluda Photo"
email: kontakt@cluda.no
description: "Website for photographers."
baseurl: "/photo" # the subpath of your site, e.g. /blog/
url: "http://cluda.github.io/photo" # the base hostname & protocol for your site
twitter_username: CludaSoftware
github_username:  cluda
icon: "/img/cluda-icon.ico"
logo: "/img/cluda_logo.png"
og_image: /img/screen-shot.jpg

include: ['.htaccess']

# Build settings
markdown: kramdown
safe: true

flickr_user: 56654375@N07

sass:
    sass_dir: _sass/black_transparent/

prose:
  rooturl: ''
  siteurl: 'http://cluda.github.io/photo/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'gallery-images'
  ignore:
    - _includes
    - _layouts
    - _sass
    - bourbon
    - css
    - neat
    - js
    - .gitignore
    - index.html
    - _config.yml
    - README.md
    - img
  metadata:
    galleries:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "Gallery Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "black_transparent/gallery"
      - name: "flickr_tag"
        field:
          element: "text"
          label: "The tag used at Flickr on the images you want to be in the gallery."
          help: "If you specify birds as the flickr_tag. This means that the 20 first pictures to be included in the gallery should have the tag birds1 on Flickr, and the next 20 pictures to be included should have the tag birds2 and so on."
      - name: "parent"
        field:
          element: "text"
          label: "Parent in Sidebar (should be 0 if no parent)"
          value: "0"
      - name: "fb-comments"
        field:
          label: "Facebook Comments"
          element: "checkbox"
          value: false
    pages:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "Page Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "black_transparent/page"
      - name: "parent"
        field:
          element: "text"
          label: "Parent in Sidebar (should be 0 if no parent)"
          value: "0"
      - name: "fb-comments"
        field:
          label: "Facebook Comments"
          element: "checkbox"
          value: false
    videos:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "Video Title"
      - name: "layout"
        field:
          element: "hidden"
          value: "black_transparent/video"
      - name: "video-id"
        field:
          element: "text"
          label: "Id of video at Vimeo. The last part of the video URL."
          help: "Example: 114487683."
      - name: "parent"
        field:
          element: "text"
          label: "Parent in Sidebar (should be 0 if no parent)"
          value: "0"
      - name: "fb-comments"
        field:
          label: "Facebook Comments"
          element: "checkbox"
          value: false